### ISSUE TITLE
Configurable commands

### ISSUE THREAD

**Issue by disktnk** [sensorbee/sensorbee#114]
Currently, SensorBee's commands are hardcoded, so fix as configurable from build.yaml on  `build_sensorbee` 

https://github.com/sensorbee/sensorbee/blob/8057c6824d64a311cdc91196ad4c751e4cfccd03/cmd/build_sensorbee/main.go#L107

**Sample1:**

build.yaml
```yaml
commands:
  runfile:
```

then `sensorbee` has only `sensorbee runfile` command.

**Sample2:**

build.yaml
```yaml
commands:
  shell:
  run:
  custom:
    pkg: repo
    path: path/to/repo
```

then `sensorbee` has `run`, `shell`, and `repo` commands. `repo` is user-customized command.

**Default:**

If no command is set-up in configuration, then `build_sensorbee` will make with default commands, `run`, `shell`, `topology`, `exp`, and `runfile`.

**Comment by disktnk** [comment]
I think this YAML schema is simpler, A key name is used as an alias for import path.

```yaml
commands:
  runfile:
  repo:
    path: path/to/repo
  repo2:
    path: path/to/repo2.v1
```

then 

```go
import (
  "gopkg.in/sensorbee/sensorbee.v0/cmd/lib/runfile"
  repo "path/to/repo"
  repo2 "path/to/repo2.v1"
)
```

But I don't know this format is actually useful or not.
